### ISSUE TITLE
Wrong popup position appearing when hovering it multiple times from different angles.

### ISSUE THREAD

**Issue by pepcus-shivani** [floating-ui/popper.js.org#59]
Both reference and popper are inside of container, when hover from different angles, tooltip's popper position gets changed.
Note: When we hover the tooltip from left, right and bottom angles tooltip appears properly, but when we hover it from top then it breaks and appears randomly somewhere on the screen.

**Comment by FezVrasta** [comment]
We don't have enough data to help you.
